### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by roughanddai** [Da-Dog/MCDR_Lockchest#1]
`[MCDR]` [16:52:44] [PT0-on_load@Lockchest/ERROR]: Error calling on_load in plugin Lockchest
Traceback (most recent call last):
  File "plugins\Lockchest.py", line 144, in on_load
    with open(json_filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: './plugins/Lockchest/key.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\MCDReforged-0.9.3-alpha\utils\plugin_thread.py", line 41, in run
    task_data.func(*task_data.args)
  File "plugins\Lockchest.py", line 147, in on_load
    saveJson()
  File "plugins\Lockchest.py", line 212, in saveJson
    with open(json_filename, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: './plugins/Lockchest/key.json'

**Comment by Da-Dog** [comment]
Will be fix in the next hour

**Comment by Da-Dog** [comment]
修复了:  892d787
